### ISSUE TITLE
Column sorting & search doesn't work

### ISSUE THREAD

**Issue by acpower7** [hyojin/material-ui-datatables#1]
It seems that none of the features advertised in this library works, including column sorting, pagination & search when I try to use the example given in the code. 
None of these features don't even work in the demo given. How can I get these features to work correctly?

thanks

**Comment by hyojin** [comment]
@acpower7 Hi! Thanks for your comment. I'm still working on and I'm going to add a live demo and apis for this component. But, so far, I have no plans for client side only pagination, search, sort.

**Comment by hyojin** [comment]
I added live demo :)
