### ISSUE TITLE
node_modules is part of installed package and should be removed

### ISSUE THREAD

**Issue by chaitanya0bhagvan** [hyojin/material-ui-datatables#14]
node_modules is part of the installed package. Presence of this node_modules containing the for dependencies material-ui-datatables is causing some unexpected errors. 

Please remove and upload a new package to npm

**Comment by hyojin** [comment]
@chaitanya0bhagvan I'm not sure what errors you have, but if you check the distributed tarball with like ```npm pack```, it doesn't contain dependencies. 

However, the reason why it has dependencies under it's directory when you install is that the library is dependent on specific version of material-ui and I think you already have different version of that.  Sometimes the most simplest way to solve dependency issue is let npm (or yarn) re-install dependencies again. [This](https://docs.npmjs.com/how-npm-works/npm3) might help you. Thanks.

**Comment by chaitanya0bhagvan** [comment]
@hyojin Looks like the older version of material-ui is getting installed because you have given a exact version number. Unless you have a strong reason to have a strict dependency on that particular version you could change it to ^0.16.4

**Comment by hyojin** [comment]
I will close this issue. if you have any concern about the version of the package, please let me know.
