### ISSUE TITLE
Sortable doesn't work if Checkbox option is enabled

### ISSUE THREAD

**Issue by shaz-dev** [hyojin/material-ui-datatables#2]
Thanks for this great module.

I've found an issue. If the checkbox/selectable options are enabled (**showCheckboxes=true**), the sort functionality doesn't work. Also, when the second column has sort functionality, if you click on first column to sort then second column gets sorted but not first one. But if you select on All checkboxes (which selects all the rows with checkbox), then first column gets sorted. Can you please help on this..

Thanks

**Comment by hyojin** [comment]
@shaz-dev Hi, Thanks for your investigation. I have a misunderstanding on a property of the material-ui component. I will fix soon :)

**Comment by hyojin** [comment]
@shaz-dev I fixed it. please check v0.16.5!
