### ISSUE TITLE
Horizontal scrolling

### ISSUE THREAD

**Issue by advance512** [hyojin/material-ui-datatables#20]
Can we add some sort of elegant solution for horizontal scrolling?

**Comment by hyojin** [comment]
Do you mean about the way to implement or improvement from UI/UX point of view?

**Comment by advance512** [comment]
I mean, scrolling left/right inside a table that is too wide for hte screen

**Comment by aziz-ka** [comment]
@advance512 I was able to achieve that by overwriting a few styles by passing the following props to `<DataTables />`:
```
tableBodyStyle: {
  overflowX: 'auto'
},
tableStyle: {
  width: 'initial'
}
```
Hope that helps

**Comment by advance512** [comment]
Great. Thanks! :)
