### ISSUE TITLE
Contents of the table disappeared when the width is small

### ISSUE THREAD

**Issue by hitlxc** [hyojin/material-ui-datatables#29]
my data is longer then the cell ,so I set  `overflow:auto` or  `overflow:scroll`  to the columns but the contents beyond the scope of the cell are disappeared ,is it a bug? Or how should I deal with this situation

**Comment by hyojin** [comment]
@hitlxc Did you try to change ```text-overflow``` property?

**Comment by hitlxc** [comment]
yeah , it worked , set `text-overflow:clip` is okay . 3q very much
