### ISSUE TITLE
checkbox and row selection event to be separate

### ISSUE THREAD

**Issue by shaz-dev** [hyojin/material-ui-datatables#3]
do you know how can I have two separate events for checkbox when checkboxes option is enabled and row/cell selection as a separate event? Currently, when selectable option is true, then cell click event doesn't work but only row selection event gets trigger which selects the checkbox. Please help..

Thanks

**Comment by hyojin** [comment]
@shaz-dev I don't think this is the best way but one of the solutions is to handle dom directly. https://facebook.github.io/react/docs/refs-and-the-dom.html 
https://facebook.github.io/react/docs/react-dom.html#finddomnode

**Comment by hyojin** [comment]
@shaz-dev When you have any other opinions, reopen it please.
