### ISSUE TITLE
A property for toggling search field in header

### ISSUE THREAD

**Issue by Yuvaleros** [hyojin/material-ui-datatables#35]
Is it possible to add a property that shows the search field in the header initially?
At this point, you must press the filter button for the search field to appear.

**Comment by hyojin** [comment]
@Yuvaleros So far, no. search filed is stateful, but it might be changed to fully stateless in the future. the other option is to hide default header and to put your component instead of it.

**Comment by hyojin** [comment]
Implemented on v0.18.2
