### ISSUE TITLE
Search with specific key

### ISSUE THREAD

**Issue by kavimaluskam** [hyojin/material-ui-datatables#41]
I would like to implement search with specific key, and so some tuning like auto complete, or select bar within it.

Sorry but may i ask if there are any hints for the customization on the search bar?

**Comment by hyojin** [comment]
@kavimaluskam So far there is no interface to customize the search bar. I think the simplest way is to hide default header and to put your component instead of it.

**Comment by hyojin** [comment]
Implemented #44
