### ISSUE TITLE
Problem in Key section.

### ISSUE THREAD

**Issue by tandonrajiv** [hyojin/material-ui-datatables#48]
I am facing problem in key section.

```
const TABLE_COLUMNS = [
  {
    key: 'names',
  } 
```

Below is my Input data.

```
const TABLE_DATA = [
  {
    names:{
             name:"ABC"
    },
   names:{
             name:"XYZ"
    }  
}
```
Is it possible with Datatable?

**Comment by hyojin** [comment]
@tandonrajiv You can define your own render function for the columns. for example,
```
// column settings
{
  key: 'names',
  render: (names, all) => <p>{names.name}</p>,
}
```

**Comment by hyojin** [comment]
@tandonrajiv I close this issue but if you have any problem related this issue, pls let me know.
