### ISSUE TITLE
Initial Sort not working, SyntaxError

### ISSUE THREAD

**Issue by akki199421** [hyojin/material-ui-datatables#55]
Syntax Error ,  Unexpected token, expected

The error is at column inside initialSort object
`
> 83 |             initialSort={column: 'Name', order: 'asc'}
  84 |             showRowHover={true}
  85 |             showHeaderToolbar={true}
  86 |             showFooterToolbar={true}`

![error](https://user-images.githubusercontent.com/7352401/29739228-45f9ccb6-8a56-11e7-993b-517845c8697a.PNG)

I am using version@0.18.2

**Comment by hyojin** [comment]
@akki199421 Hi, have you tried ```initialSort={{column: 'Name', order: 'asc'}}```?
(because it's an object.)

**Comment by akki199421** [comment]
Yeah, i didn't realize that. Thanks.
