### ISSUE TITLE
TypeError: Cannot read property 'baseTheme' of undefined

### ISSUE THREAD

**Issue by ilyasahsan123** [hyojin/material-ui-datatables#79]
hallo, i have issue like this:
`getStyles
  93 | // customized components
  94 | function getStyles(props, context) {
  95 |   var _context$muiTheme = context.muiTheme,
> 96 |       palette = _context$muiTheme.baseTheme.palette,
  97 |       table = _context$muiTheme.table,
  98 |       tableHeaderColumn = _context$muiTheme.tableHeaderColumn;
  99 | `

**Comment by lummish** [comment]
Same here. What version of the material-ui package are you using? I had no problems until I upgraded to the new beta

**Comment by ilyasahsan123** [comment]
The latest material ui with latest react

**Comment by lentyai2** [comment]
This very nice table wouldn't work with the material-ui v.1 - they introduced the whole new API and 
 broke a bunch of stuff. Note: "Now material-ui provides example code of data tables component with it's v1.0.0 package" on the front page of this repo. It's lacking a bunch of functionality though.
