### ISSUE TITLE
Warning in latest version of React

### ISSUE THREAD

**Issue by advance512** [hyojin/material-ui-datatables#9]
```
Warning: Failed prop type: Invalid prop `children` supplied to `DataTablesRowColumn`, expected a ReactNode
```

**Comment by hyojin** [comment]
@advance512 Hi! I've tried with React 15.4.2, but It seems like not a version problem of React. Does your data contain anything except number, string, array? or can you show me your settings?

**Comment by advance512** [comment]
Uhm, booleans? dates?
I do convert them to strings, though (at least now).

BTW, do you have any way to input translation funcs for data items, to convert them internally to presentable formats? Or a per-type translation func?

**Comment by hyojin** [comment]
Currently it doesn't have. you need to convert before rendering datatables.
but I will consider :)

**Comment by advance512** [comment]
I added it myself. I was also happy to see you can add React components (like Avatar from MaterialUI) to the datatable. That means I have a formatting func that receives an imageURL and returns an Avatar component showing that image. 

Cool stuff :)

**Comment by advance512** [comment]
fyi, I added react controls. I made sure the search searches the "origin" member, but displays another (React control, e.g. image element based on URL).

I should share it, acutally..
